# Generated by Django 3.0.5 on 2020-06-06 17:50

import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=articles.models.upload_path, verbose_name='Image')),
                ('content', models.TextField(verbose_name='Content')),
                ('summary', models.CharField(blank=True, max_length=511, null=True, verbose_name='Summery')),
                ('attach', models.FileField(blank=True, null=True, upload_to=articles.models.upload_path, verbose_name='Attach')),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='Created')),
                ('updated', django_jalali.db.models.jDateField(auto_now=True, verbose_name='Updated')),
                ('read_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Time to read')),
                ('status', models.CharField(choices=[('delete', 'delete'), ('draft', 'draft'), ('publish', 'publish')], default='draft', max_length=32, verbose_name='Status')),
                ('publish', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Publish')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publish', 'title'],
            },
        ),
    ]
